name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and tools
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest flake8 black isort

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest
          else
            echo "No tests found."
          fi

      - name: Run lint checks (flake8, black, isort)
        run: |
          echo "Running flake8..."
          flake8 . || exit 1

          echo "Running black --check..."
          black . --check || exit 1

          echo "Running isort --check-only..."
          isort . --check-only || exit 1
